import StyledComponentsRegistry from "@/utils/Registery";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
// import "./globals.scss";
import { Inter } from "next/font/google";
import { PageLayout } from "@/components/PageLayout/";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Travel Itineray",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Agdasima&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@100&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <PageLayout>{children}</PageLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
